### this is a good next QC step after the automated QC, we'll start at the longest duration (72 hours), and then remove the obviously bad points at these timescales all the way down to 24 hours. we'll look visually at the 1000-yr, 72-hr maps to identify the obviously bad points at these timescales (which should be some of the most egregious)

### do this after running the automated QC with "find_exceedances_qc_vs_prism"

In [2]:
import pandas as pd
import os

In [3]:
duration = 72
dataset = "stage4" ### which dataset to analyze

year = 2002

workdir = "/glade/work/rschumac/precip_data/extremerain/"

#### read in the exceedance files into pandas dataframes

In [4]:
df100_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y72h.csv")
df10_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y72h.csv")
try:
    df1000_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y72h.csv")
except:  ## if no rows, just make an empty dataframe with the right columns
    df1000_72h = pd.DataFrame(columns=df_72h.columns)

### and the 48-h ones
df100_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y48h.csv")
df10_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y48h.csv")
try:
    df1000_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y48h.csv")
except:
    df1000_48h = pd.DataFrame(columns=df_48h.columns)

### and the 24-h ones
df100_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y24h.csv")
df10_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y24h.csv")
try:
    df1000_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y24h.csv")
except:
    df1000_24h = pd.DataFrame(columns=df_48h.columns)

In [5]:
df1000_72h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2002-03-19 12:00:00,36.625000,-82.458333,197.08430,2.317942,1.011901,1
1,2002-03-19 12:00:00,36.666667,-82.458333,204.85568,0.040362,1.000197,1
2,2002-06-23 12:00:00,34.458333,-105.708333,178.53607,17.726557,1.110233,3
3,2002-07-03 12:00:00,29.375000,-98.791667,576.11316,4.740135,1.008296,1
4,2002-07-03 12:00:00,29.375000,-98.750000,585.35425,13.828816,1.024196,1
...,...,...,...,...,...,...,...
167,2002-11-10 12:00:00,35.500000,-118.333333,385.33936,26.172216,1.072869,0
168,2002-11-10 12:00:00,35.541667,-118.416667,401.52237,36.214453,1.099134,0
169,2002-11-10 12:00:00,35.541667,-118.375000,405.70746,38.360768,1.104427,0
170,2002-11-10 12:00:00,35.541667,-118.333333,383.73334,10.198246,1.027302,0
171,2002-11-10 12:00:00,35.708333,-118.500000,440.55057,11.976165,1.027944,0

#### and the files with the removed points, output from the automated QC algorithm

In [6]:
removed1000_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y72h.csv")
removed100_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y72h.csv")
removed10_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y72h.csv")

removed1000_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y48h.csv")
removed100_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y48h.csv")
removed10_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y48h.csv")

removed1000_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y24h.csv")
removed100_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y24h.csv")
removed10_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y24h.csv")


removed1000_72h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2002-03-17 12:00:00,38.500000,-112.291667,118.161705,2.068122,1.017814,0
1,2002-03-18 12:00:00,38.458333,-112.291667,103.767944,1.615988,1.015819,1
2,2002-03-18 12:00:00,38.500000,-112.291667,119.707620,3.614036,1.031130,1
3,2002-07-21 12:00:00,32.041667,-106.000000,238.840700,21.960955,1.101259,0
4,2002-07-21 12:00:00,32.041667,-105.958333,298.575930,70.500375,1.309110,0
5,2002-07-21 12:00:00,32.791667,-107.750000,214.632900,25.445260,1.134497,0
6,2002-07-21 12:00:00,33.041667,-106.750000,220.551210,50.500478,1.296973,0
7,2002-07-21 12:00:00,33.041667,-106.708333,179.465240,9.470780,1.055712,0
8,2002-07-22 12:00:00,32.041667,-106.000000,231.225170,14.345431,1.066145,1
9,2002-07-22 12:00:00,32.041667,-105.958333,289.290470,61.214914,1.268398,1
10,2002-07-22 12:00:00,33.041667,-106.750000,236.809900,66.759175,1.392584,1
11,2002-07-22 12:00:00,33.041667,-106.708333,188.114720,18.120256,1.106593,1
12,2002-07-23 12:00:00,32.041667,-105.958333,273.147640,45.072092,1.197619,0
13,2002-07-23 12:00:00,33.041667,-106.750000,247.791240,77.740514,1.457161,0
14,2002-07-23 12:00:00,33.041667,-106.708333,182.210110,12.215653,1.071859,0
15,2002-07-27 12:00:00,32.041667,-105.958333,231.206710,3.131159,1.013729,1
16,2002-07-28 12:00:00,32.041667,-105.958333,241.800350,13.724802,1.060177,1
17,2002-07-29 12:00:00,32.750000,-107.708333,178.298930,5.450408,1.031533,0
18,2002-07-29 12:00:00,34.916667,-107.833333,121.610410,6.542194,1.056855,0
19,2002-07-30 12:00:00,34.916667,-107.833333,121.610410,6.542194,1.056855,1
20,2002-10-03 12:00:00,40.916667,-110.625000,156.314120,3.759541,1.024644,1
21,2002-10-14 12:00:00,42.750000,-77.833333,269.735700,63.132087,1.305571,1
22,2002-10-15 12:00:00,42.750000,-77.833333,269.735700,63.132087,1.305571,1
23,2002-10-16 12:00:00,42.750000,-77.833333,270.507870,63.904274,1.309309,0
24,2002-11-21 12:00:00,36.166667,-82.458333,277.977500,63.682677,1.297173,0
25,2002-11-22 12:00:00,36.166667,-82.458333,304.758540,90.463714,1.422146,0
26,2002-11-23 12:00:00,36.166667,-82.458333,283.552550,69.257720,1.323189,0
27,2002-12-25 12:00:00,33.375000,-111.750000,193.832300,44.657113,1.299360,0
28,2002-12-26 12:00:00,33.375000,-111.750000,193.123730,43.948540,1.294610,0
29,2002-12-27 12:00:00,33.375000,-111.750000,179.945890,30.770699,1.206272,0
30,2002-09-11 12:00:00,34.750000,-108.125000,121.335610,0.160058,1.001321,1
31,2002-09-11 12:00:00,34.791667,-108.125000,136.057370,14.450324,1.118828,1
32,2002-09-11 12:00:00,34.791667,-108.083333,135.102140,16.490113,1.139026,1
33,2002-09-11 12:00:00,34.791667,-108.041667,119.088170,2.530439,1.021710,1
34,2002-09-11 12:00:00,34.833333,-108.125000,134.913970,12.876268,1.105511,1
35,2002-09-11 12:00:00,34.833333,-108.083333,136.238310,17.728008,1.149590,1

### subset down to just events for each threshold, for looping

In [7]:
events1000_72h = df1000_72h.drop_duplicates(['time','event_num'])
events100_72h = df100_72h.drop_duplicates(['time','event_num'])
events10_72h = df10_72h.drop_duplicates(['time','event_num'])

print("1000-yr events: "+str(len(events1000_72h)))
print("100-yr events: "+str(len(events100_72h)))
print("10-yr events: "+str(len(events10_72h)))

events1000_72h

1000-yr events: 17
100-yr events: 126
10-yr events: 666

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2002-03-19 12:00:00,36.625000,-82.458333,197.08430,2.317942,1.011901,1
2,2002-06-23 12:00:00,34.458333,-105.708333,178.53607,17.726557,1.110233,3
3,2002-07-03 12:00:00,29.375000,-98.791667,576.11316,4.740135,1.008296,1
9,2002-07-04 12:00:00,28.625000,-99.458333,486.48108,4.312878,1.008945,0
13,2002-07-06 12:00:00,41.000000,-101.791667,238.21497,30.668853,1.147769,5
16,2002-07-07 12:00:00,40.958333,-102.000000,204.81892,2.525245,1.012483,2
49,2002-07-08 12:00:00,40.958333,-102.000000,204.81892,2.525245,1.012483,4
82,2002-08-22 12:00:00,42.333333,-89.958333,257.35803,6.106611,1.024305,2
86,2002-08-23 12:00:00,42.333333,-90.000000,257.77070,6.545758,1.026055,1
93,2002-08-24 12:00:00,42.333333,-90.000000,258.17720,6.952252,1.027673,1
100,2002-09-11 12:00:00,34.500000,-108.083333,115.81517,0.118823,1.001027,1
109,2002-09-12 12:00:00,34.416667,-108.125000,131.45543,11.873463,1.099291,1
142,2002-09-13 12:00:00,34.541667,-108.125000,114.67241,0.087981,1.000768,0
145,2002-09-15 12:00:00,31.000000,-84.916667,504.74832,4.655971,1.009310,0
147,2002-09-16 12:00:00,31.000000,-84.916667,509.40063,9.308284,1.018613,0
151,2002-09-23 12:00:00,33.375000,-85.750000,373.24832,2.986090,1.008065,0
164,2002-11-10 12:00:00,35.458333,-118.333333,352.39838,7.962970,1.023119,0

### now move the maps, so the ones retained at each ARI are in their own directories

In [8]:
os.system("mkdir -p "+dataset+"/auto_qc/72h/"+str(year)+"/maps/retained1000 "+dataset+"/auto_qc/72h/"+str(year)+"/maps/retained100 "+dataset+"/auto_qc/72h/"+str(year)+"/maps/retained10")

print("running 1000y")
for i, row in events1000_72h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/retained1000/.")

print("running 100y")
for i, row in events100_72h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/retained100/.")

print("running 10y")
for i, row in events10_72h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/retained10/.")

running 1000y
running 100y

mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070612_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070712_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070812_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002092312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002111012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002012512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002032012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002032012_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002032112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060512_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060612_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060712_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061212_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061212_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061512_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061612_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062212_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062312_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062312_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062512_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070512_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070512_6.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070612_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070612_8.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070712_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070712_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070812_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070812_7.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070912_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070912_6.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002071012_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072512_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002073012_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002073112_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080812_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080912_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081012_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081712_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082112_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082212_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082312_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082412_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082512_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082712_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082712_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082712_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082812_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082912_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002083012_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002083112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090112_6.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090212_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090712_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090812_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091412_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002092212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002092312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002092412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002092712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002092812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002100212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002100312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002103112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002110912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002111012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002111112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002121612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002121712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002012112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002012212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002012412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002012512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002012612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002022112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002022212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002030312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002030412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002030512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002030912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002032012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002032012_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002032112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002032112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002032812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002032912_0.png': No such file or directory

running 10y

mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002033112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002033112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002040112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002040112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002040112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002040212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002040312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002040512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002040812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002040812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002040912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002040912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002041012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002041012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002041412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002041512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002041612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002041712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002041812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002041912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002041912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002041912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042012_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042112_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042812_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002043012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002051012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002051012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002051212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002051312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002051312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002051412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002051412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002051512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002051612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002051712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002051812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002051812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002051912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002052912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002053012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002053112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002053112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002053112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060112_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060112_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060412_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060412_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060512_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060512_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060512_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060512_6.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060612_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060612_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060612_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060612_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060712_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060712_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060712_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060812_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060912_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061212_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061212_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061212_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061312_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061312_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061412_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061512_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061612_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061612_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061612_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061712_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061712_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061812_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061812_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062012_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062112_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062212_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062212_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062212_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062312_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062312_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062312_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062512_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062512_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062612_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062612_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062712_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062712_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062912_1.png': No such file or directory

### now repeat for the removed ones, sorting map files into directories for the highest ARI on which they were removed
#### note that some events have both retained and removed points. The ones with some retained points will have already been moved, so these will be just the events that were completely removed

In [9]:
removed_events1000_72h = removed1000_72h.drop_duplicates(['time','event_num'])
removed_events100_72h = removed100_72h.drop_duplicates(['time','event_num'])
removed_events10_72h = removed10_72h.drop_duplicates(['time','event_num'])

print("removed 1000-yr events: "+str(len(removed_events1000_72h)))
print("removed 100-yr events: "+str(len(removed_events100_72h)))
print("removed 10-yr events: "+str(len(removed_events10_72h)))

removed 1000-yr events: 20
removed 100-yr events: 51
removed 10-yr events: 215

In [10]:
os.system("mkdir -p "+dataset+"/auto_qc/72h/"+str(year)+"/maps/removed1000 "+dataset+"/auto_qc/72h/"+str(year)+"/maps/removed100 "+dataset+"/auto_qc/72h/"+str(year)+"/maps/removed10")

print("running 1000y")
for i, row in removed_events1000_72h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/removed1000/.")

print("running 100y")
for i, row in removed_events100_72h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/removed100/.")

print("running 10y")
for i, row in removed_events10_72h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/removed10/.")

mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002073012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002100312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002112112_0.png': No such file or directory

running 1000y
running 100y

mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002112212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002112312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002013012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002013112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002071012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002071112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002071912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002073012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002100212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002100312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002100412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002100912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002103012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002111112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002112112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002112212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002112312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002120612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002120712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002120812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002010512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002010612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002010712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002011212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002011312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002011412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002011512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002011612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002011712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002013012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002013112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002020112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002030312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002030412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002030512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002031912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002032012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002032112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042012_1.png': No such file or directory

running 10y

mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042812_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002042912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002043012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002043012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002050712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060812_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002060912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061412_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061712_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002061912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062112_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062212_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062212_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062312_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062512_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062612_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002062912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002063012_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070312_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070412_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070512_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070612_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070612_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070712_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070712_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070812_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070812_8.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002070912_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002071012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002071112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002071212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002071512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002071612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002071712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002071812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002071912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072012_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072212_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072512_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072612_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072612_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072712_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002072912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002073012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002073012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002073112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002073112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080412_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002080912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081012_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002081912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082412_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082512_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082712_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002082912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002083012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002083012_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002083112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002083112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002083112_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002083112_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090112_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002090912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002092012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002092112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002092512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002092612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002092712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002100212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002100312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002100412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002100712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002100812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002100912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002101712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002102412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002102512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002102512_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002102612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002102712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002102812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002102912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002103012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002110112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002110912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002111012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002111112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002111512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002111612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002111712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002111712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002111812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002111912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002112112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002112212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002112312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002112412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002112512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002112612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002120612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002120712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002120812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002121812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002121812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002121912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002121912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002122812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/72h/2002/maps/qc_check_2002091112_1.png': No such file or directory

## Pause here!

#### now, take a look at the maps for these cases (under "retained1000", for example)

#### if we want to remove a row because it's bad, specify the row(s) in the 1000-year dataframe

In [16]:
df1000_72h[df1000_72h.time=='2002-09-13 12:00:00']

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
142,2002-09-13 12:00:00,34.541667,-108.125,114.672410,0.087981,1.000768,0
143,2002-09-13 12:00:00,34.583333,-108.125,115.121520,0.345499,1.003010,0
144,2002-09-13 12:00:00,34.791667,-108.125,123.082756,1.475707,1.012135,0

In [17]:
####           ### which index(es) to drop?
#to_drop = [0,1,2] + list(range(40,50))
           
           #### this needs to be user-specified based on manual inspection!!
to_drop = list(range(100,145))
#to_drop = []
####

rows_to_drop_visual = df1000_72h.loc[to_drop]
rows_to_drop_visual

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
100,2002-09-11 12:00:00,34.500000,-108.083333,115.815170,0.118823,1.001027,1
101,2002-09-11 12:00:00,34.625000,-108.125000,122.995190,6.670869,1.057347,1
102,2002-09-11 12:00:00,34.666667,-108.125000,133.187160,15.138677,1.128241,1
103,2002-09-11 12:00:00,34.750000,-108.125000,121.335610,0.160058,1.001321,1
104,2002-09-11 12:00:00,34.791667,-108.125000,136.057370,14.450324,1.118828,1
105,2002-09-11 12:00:00,34.791667,-108.083333,135.102140,16.490113,1.139026,1
106,2002-09-11 12:00:00,34.791667,-108.041667,119.088170,2.530439,1.021710,1
107,2002-09-11 12:00:00,34.833333,-108.125000,134.913970,12.876268,1.105511,1
108,2002-09-11 12:00:00,34.833333,-108.083333,136.238310,17.728008,1.149590,1
109,2002-09-12 12:00:00,34.416667,-108.125000,131.455430,11.873463,1.099291,1
110,2002-09-12 12:00:00,34.458333,-108.166667,126.925530,8.922936,1.075616,1
111,2002-09-12 12:00:00,34.458333,-108.125000,134.749180,18.133441,1.155497,1
112,2002-09-12 12:00:00,34.458333,-108.083333,124.548134,7.759392,1.066440,1
113,2002-09-12 12:00:00,34.500000,-108.208333,125.022410,6.433853,1.054254,1
114,2002-09-12 12:00:00,34.500000,-108.166667,123.616670,6.933972,1.059426,1
115,2002-09-12 12:00:00,34.500000,-108.125000,133.130250,18.575503,1.162154,1
116,2002-09-12 12:00:00,34.500000,-108.083333,136.401060,20.704715,1.178957,1
117,2002-09-12 12:00:00,34.541667,-108.208333,125.347145,7.292495,1.061772,1
118,2002-09-12 12:00:00,34.541667,-108.166667,120.283750,4.058339,1.034918,1
119,2002-09-12 12:00:00,34.541667,-108.125000,132.708050,18.123626,1.158168,1
120,2002-09-12 12:00:00,34.541667,-108.083333,129.043260,14.085109,1.122524,1
121,2002-09-12 12:00:00,34.583333,-108.166667,123.496630,6.407742,1.054725,1
122,2002-09-12 12:00:00,34.583333,-108.125000,132.295850,17.519831,1.152644,1
123,2002-09-12 12:00:00,34.583333,-108.083333,127.055405,14.408156,1.127905,1
124,2002-09-12 12:00:00,34.625000,-108.166667,120.627304,1.457990,1.012235,1
125,2002-09-12 12:00:00,34.625000,-108.125000,139.875060,23.550737,1.202458,1
126,2002-09-12 12:00:00,34.625000,-108.083333,117.691650,4.133679,1.036401,1
127,2002-09-12 12:00:00,34.666667,-108.166667,125.744125,4.668890,1.038562,1
128,2002-09-12 12:00:00,34.666667,-108.125000,149.486370,31.437886,1.266313,1
129,2002-09-12 12:00:00,34.666667,-108.083333,117.946810,3.628601,1.031741,1
130,2002-09-12 12:00:00,34.708333,-108.125000,133.932280,13.825780,1.115113,1
131,2002-09-12 12:00:00,34.708333,-108.083333,126.286790,10.089887,1.086834,1
132,2002-09-12 12:00:00,34.750000,-108.125000,135.837570,14.662019,1.120998,1
133,2002-09-12 12:00:00,34.750000,-108.083333,124.708725,6.758616,1.057301,1
134,2002-09-12 12:00:00,34.791667,-108.166667,131.063190,6.357012,1.050976,1
135,2002-09-12 12:00:00,34.791667,-108.125000,149.434570,27.827521,1.228831,1
136,2002-09-12 12:00:00,34.791667,-108.083333,149.607760,30.995729,1.261320,1
137,2002-09-12 12:00:00,34.791667,-108.041667,127.522990,10.965254,1.094076,1
138,2002-09-12 12:00:00,34.833333,-108.166667,126.479230,0.833138,1.006631,1
139,2002-09-12 12:00:00,34.833333,-108.125000,142.568620,20.530916,1.168234,1
140,2002-09-12 12:00:00,34.833333,-108.083333,144.985200,26.474895,1.223397,1
141,2002-09-12 12:00:00,34.833333,-108.041667,118.792015,2.030295,1.017388,1
142,2002-09-13 12:00:00,34.541667,-108.125000,114.672410,0.087981,1.000768,0
143,2002-09-13 12:00:00,34.583333,-108.125000,115.121520,0.345499,1.003010,0
144,2002-09-13 12:00:00,34.791667,-108.125000,123.082756,1.475707,1.012135,0

#### find any other points within a small radius around these (say 0.10 degrees in each direction)
#### furthermore, find points in the 100- and 10-year files on the same day and in the same radius, in all 3 durations (72,48,24)

In [18]:
latlon_buf = 0.10  ## lat/lon buffer around the centerpoint

rows_to_drop_1000_72h = removed1000_72h
rows_to_drop_100_72h = removed100_72h
rows_to_drop_10_72h = removed10_72h
rows_to_drop_1000_48h = removed1000_48h
rows_to_drop_100_48h = removed100_48h
rows_to_drop_10_48h = removed10_48h
rows_to_drop_1000_24h = removed1000_24h
rows_to_drop_100_24h = removed100_24h
rows_to_drop_10_24h = removed10_24h

for i in range(0,len(rows_to_drop_visual)):
    this_lon = rows_to_drop_visual.iloc[i].lon
    this_lat = rows_to_drop_visual.iloc[i].lat
    this_time = rows_to_drop_visual.iloc[i].time
    
    more_rows_to_drop_1000_72h = df1000_72h[(df1000_72h.time==this_time) & (df1000_72h.lon >= this_lon-latlon_buf) & (df1000_72h.lon <= this_lon+latlon_buf) & (df1000_72h.lat >= this_lat-latlon_buf) & (df1000_72h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_72h = pd.concat([rows_to_drop_1000_72h,more_rows_to_drop_1000_72h])

    ### now also find the rows in the same area in the 100 & 10-year files
    more_rows_to_drop_100_72h = df100_72h[(df100_72h.time==this_time) & (df100_72h.lon >= this_lon-latlon_buf) & (df100_72h.lon <= this_lon+latlon_buf) & (df100_72h.lat >= this_lat-latlon_buf) & (df100_72h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_72h = df10_72h[(df10_72h.time==this_time) & (df10_72h.lon >= this_lon-latlon_buf) & (df10_72h.lon <= this_lon+latlon_buf) & (df10_72h.lat >= this_lat-latlon_buf) & (df10_72h.lat <= this_lat+latlon_buf)] 

    rows_to_drop_100_72h = pd.concat([rows_to_drop_100_72h,more_rows_to_drop_100_72h])
    rows_to_drop_10_72h = pd.concat([rows_to_drop_10_72h,more_rows_to_drop_10_72h])  

    ### repeat for 48h
    more_rows_to_drop_1000_48h = df1000_48h[(df1000_48h.time==this_time) & (df1000_48h.lon >= this_lon-latlon_buf) & (df1000_48h.lon <= this_lon+latlon_buf) & (df1000_48h.lat >= this_lat-latlon_buf) & (df1000_48h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_48h = pd.concat([rows_to_drop_1000_48h,more_rows_to_drop_1000_48h])
    more_rows_to_drop_100_48h = df100_48h[(df100_48h.time==this_time) & (df100_48h.lon >= this_lon-latlon_buf) & (df100_48h.lon <= this_lon+latlon_buf) & (df100_48h.lat >= this_lat-latlon_buf) & (df100_48h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_48h = df10_48h[(df10_48h.time==this_time) & (df10_48h.lon >= this_lon-latlon_buf) & (df10_48h.lon <= this_lon+latlon_buf) & (df10_48h.lat >= this_lat-latlon_buf) & (df10_48h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_100_48h = pd.concat([rows_to_drop_100_48h,more_rows_to_drop_100_48h])
    rows_to_drop_10_48h = pd.concat([rows_to_drop_10_48h,more_rows_to_drop_10_48h])  

    ### and 24
    more_rows_to_drop_1000_24h = df1000_24h[(df1000_24h.time==this_time) & (df1000_24h.lon >= this_lon-latlon_buf) & (df1000_24h.lon <= this_lon+latlon_buf) & (df1000_24h.lat >= this_lat-latlon_buf) & (df1000_24h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_24h = pd.concat([rows_to_drop_1000_24h,more_rows_to_drop_1000_24h])
    
    ### now also find the rows in the same area in the 100 & 10-year files
    more_rows_to_drop_100_24h = df100_24h[(df100_24h.time==this_time) & (df100_24h.lon >= this_lon-latlon_buf) & (df100_24h.lon <= this_lon+latlon_buf) & (df100_24h.lat >= this_lat-latlon_buf) & (df100_24h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_24h = df10_24h[(df10_24h.time==this_time) & (df10_24h.lon >= this_lon-latlon_buf) & (df10_24h.lon <= this_lon+latlon_buf) & (df10_24h.lat >= this_lat-latlon_buf) & (df10_24h.lat <= this_lat+latlon_buf)] 
    
    rows_to_drop_100_24h = pd.concat([rows_to_drop_100_24h,more_rows_to_drop_100_24h])
    rows_to_drop_10_24h = pd.concat([rows_to_drop_10_24h,more_rows_to_drop_10_24h])  

#### drop duplicates
rows_to_drop_1000_72h = rows_to_drop_1000_72h.drop_duplicates()
rows_to_drop_100_72h.drop_duplicates(inplace=True)
rows_to_drop_10_72h.drop_duplicates(inplace=True)
rows_to_drop_1000_48h = rows_to_drop_1000_48h.drop_duplicates()
rows_to_drop_100_48h.drop_duplicates(inplace=True)
rows_to_drop_10_48h.drop_duplicates(inplace=True)
rows_to_drop_1000_24h = rows_to_drop_1000_24h.drop_duplicates()
rows_to_drop_100_24h.drop_duplicates(inplace=True)
rows_to_drop_10_24h.drop_duplicates(inplace=True)

rows_to_drop_100_72h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2002-01-30 12:00:00,40.833333,-111.791667,174.087510,12.998863,1.080694,0
1,2002-01-30 12:00:00,40.833333,-111.750000,179.057980,12.561396,1.075445,0
2,2002-01-30 12:00:00,40.875000,-111.750000,183.277710,1.917311,1.010572,0
3,2002-01-31 12:00:00,40.833333,-111.791667,162.694410,1.605766,1.009968,0
4,2002-03-10 12:00:00,26.250000,-81.791667,419.388670,30.487553,1.078394,0
...,...,...,...,...,...,...,...
2219,2002-09-13 12:00:00,34.791667,-108.125000,123.082756,32.384649,1.357060,0
2220,2002-09-13 12:00:00,34.791667,-108.083333,117.414055,28.695937,1.323451,0
2221,2002-09-13 12:00:00,34.791667,-108.041667,96.382410,8.931794,1.102135,0
2222,2002-09-13 12:00:00,34.833333,-108.125000,108.851490,17.900104,1.196810,0
2223,2002-09-13 12:00:00,34.833333,-108.083333,105.867780,17.225745,1.194329,0

#### now drop those rows from the original dataframes. Method from here: https://www.includehelp.com/python/how-to-remove-rows-in-a-pandas-dataframe-if-the-same-row-exists-in-another-dataframe.aspx#:~:text=df1%20and%20df2.-,Remove%20rows%20in%20a%20Pandas%20dataframe%20if%20the%20same%20row,then%20drop%20the%20common%20rows.

In [19]:
df1000_72h_edit = pd.merge(df1000_72h,rows_to_drop_1000_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_72h_edit = pd.merge(df100_72h,rows_to_drop_100_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_72h_edit = pd.merge(df10_72h,rows_to_drop_10_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_72h length went from "+str(len(df1000_72h))+" to "+str(len(df1000_72h_edit)))
print("df100_72h length went from "+str(len(df100_72h))+" to "+str(len(df100_72h_edit)))
print("df10_72h length went from "+str(len(df10_72h))+" to "+str(len(df10_72h_edit)))

#### 48h
df1000_48h_edit = pd.merge(df1000_48h,rows_to_drop_1000_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_48h_edit = pd.merge(df100_48h,rows_to_drop_100_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_48h_edit = pd.merge(df10_48h,rows_to_drop_10_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_48h length went from "+str(len(df1000_48h))+" to "+str(len(df1000_48h_edit)))
print("df100_48h length went from "+str(len(df100_48h))+" to "+str(len(df100_48h_edit)))
print("df10_48h length went from "+str(len(df10_48h))+" to "+str(len(df10_48h_edit)))

### 24h
df1000_24h_edit = pd.merge(df1000_24h,rows_to_drop_1000_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_24h_edit = pd.merge(df100_24h,rows_to_drop_100_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_24h_edit = pd.merge(df10_24h,rows_to_drop_10_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_24h length went from "+str(len(df1000_24h))+" to "+str(len(df1000_24h_edit)))
print("df100_24h length went from "+str(len(df100_24h))+" to "+str(len(df100_24h_edit)))
print("df10_24h length went from "+str(len(df10_24h))+" to "+str(len(df10_24h_edit)))

df1000_72h length went from 172 to 127
df100_72h length went from 2801 to 2631
df10_72h length went from 56166 to 55911
df1000_48h length went from 112 to 87
df100_48h length went from 1664 to 1535
df10_48h length went from 37666 to 37470
df1000_24h length went from 56 to 47
df100_24h length went from 749 to 695
df10_24h length went from 18086 to 17994

In [20]:
df1000_72h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y72h_edit.csv", index=False)
df100_72h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y72h_edit.csv", index=False)
df10_72h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y72h_edit.csv", index=False)

rows_to_drop_1000_72h.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y72h.csv", index=False)
rows_to_drop_100_72h.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y72h.csv", index=False)
rows_to_drop_10_72h.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y72h.csv", index=False)
                             
#### 48h
df1000_48h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y48h_edit.csv", index=False)
df100_48h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y48h_edit.csv", index=False)
df10_48h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y48h_edit.csv", index=False)

rows_to_drop_1000_48h.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y48h.csv", index=False)
rows_to_drop_100_48h.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y48h.csv", index=False)
rows_to_drop_10_48h.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y48h.csv", index=False)  

### 24h
df1000_24h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y24h_edit.csv", index=False)
df100_24h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y24h_edit.csv", index=False)
df10_24h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y24h_edit.csv", index=False)

rows_to_drop_1000_24h.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y24h.csv", index=False)
rows_to_drop_100_24h.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y24h.csv", index=False)
rows_to_drop_10_24h.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y24h.csv", index=False)

In [52]:
rows_to_drop_1000_72h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2014-02-28 12:00:00,45.541667,-113.625000,98.266260,2.584460,1.027011,0
1,2014-02-28 12:00:00,45.541667,-113.583333,93.865890,2.552892,1.027958,0
2,2014-02-28 12:00:00,45.583333,-113.583333,94.666016,4.851617,1.054018,0
3,2014-02-28 12:00:00,45.583333,-113.541667,93.890760,8.495965,1.099490,0
4,2014-02-28 12:00:00,45.583333,-113.500000,91.915540,10.635543,1.130851,0
...,...,...,...,...,...,...,...
2161,2014-07-15 12:00:00,32.916667,-108.916667,214.523930,56.213826,1.355087,0
2162,2014-07-15 12:00:00,32.916667,-108.875000,190.735340,35.013403,1.224846,0
2163,2014-09-28 12:00:00,36.291667,-115.000000,104.211750,1.262112,1.012260,2
2164,2014-09-29 12:00:00,36.291667,-115.000000,104.211750,1.262112,1.012260,2
312,2014-09-30 12:00:00,43.083333,-109.708333,160.307790,2.751589,1.017464,3