### Now move on to 1000-yr, 48-h 

### do this after running the automated QC with "find_exceedances_qc_vs_prism" and running step 2 (72 h)

In [1]:
import pandas as pd
import os

In [2]:
duration = 48
dataset = "stage4" ### which dataset to analyze

year = 2002

workdir = "/glade/work/rschumac/precip_data/extremerain/"

#### read in the exceedance files into pandas dataframes - note that now we're reading in the cleaned, edited files that were created in the 72h step

In [3]:
df100_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y72h_edit.csv")
df10_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y72h_edit.csv")
try:
    df1000_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y72h_edit.csv")
except:  ## if no rows, just make an empty dataframe with the right columns
    df1000_72h = pd.DataFrame(columns=df_72h.columns)

### and the 48-h ones
df100_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y48h_edit.csv")
df10_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y48h_edit.csv")
try:
    df1000_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y48h_edit.csv")
except:
    df1000_48h = pd.DataFrame(columns=df_48h.columns)

### and the 24-h ones
df100_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y24h_edit.csv")
df10_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y24h_edit.csv")
try:
    df1000_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y24h_edit.csv")
except:
    df1000_24h = pd.DataFrame(columns=df_48h.columns)

In [4]:
df1000_48h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2002-03-18 12:00:00,36.625000,-82.458333,192.65015,10.208249,1.055953,0
1,2002-03-18 12:00:00,36.666667,-82.458333,200.58293,7.651965,1.039662,0
2,2002-06-23 12:00:00,44.208333,-89.625000,258.13940,2.597104,1.010163,2
3,2002-07-06 12:00:00,41.000000,-101.833333,203.07721,6.430487,1.032701,2
4,2002-07-06 12:00:00,41.000000,-101.791667,238.21497,41.087483,1.208431,2
...,...,...,...,...,...,...,...
82,2002-11-09 12:00:00,35.500000,-118.333333,340.51965,24.548311,1.077692,0
83,2002-11-09 12:00:00,35.541667,-118.416667,353.16852,34.646071,1.108771,0
84,2002-11-09 12:00:00,35.541667,-118.375000,357.16410,35.920128,1.111816,0
85,2002-11-09 12:00:00,35.541667,-118.333333,338.41130,11.682663,1.035756,0
86,2002-11-09 12:00:00,35.708333,-118.500000,386.37030,17.758274,1.048176,0

#### and the files with the removed points, output from the automated QC algorithm (plus any that were removed in the 72h step)

In [5]:
removed1000_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y72h.csv")
removed100_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y72h.csv")
removed10_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y72h.csv")

removed1000_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y48h.csv")
removed100_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y48h.csv")
removed10_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y48h.csv")

removed1000_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y24h.csv")
removed100_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y24h.csv")
removed10_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y24h.csv")

removed1000_48h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2002-03-16 12:00:00,38.458333,-112.291667,93.561600,0.922073,1.009953,0
1,2002-03-16 12:00:00,38.500000,-112.291667,109.329544,5.007713,1.048003,0
2,2002-03-17 12:00:00,38.458333,-112.333333,157.548970,8.113620,1.054295,0
3,2002-03-17 12:00:00,38.458333,-112.291667,99.029610,6.390083,1.068978,0
4,2002-03-17 12:00:00,38.500000,-112.291667,115.266370,10.944542,1.104911,0
5,2002-07-21 12:00:00,32.041667,-106.000000,209.590210,5.111227,1.024996,0
6,2002-07-21 12:00:00,32.041667,-105.958333,260.978450,46.871535,1.218916,0
7,2002-07-21 12:00:00,33.041667,-106.750000,203.039020,48.609516,1.314768,0
8,2002-07-21 12:00:00,33.041667,-106.708333,160.536180,6.434948,1.041758,0
9,2002-07-22 12:00:00,33.041667,-106.750000,197.579300,43.149799,1.279414,1
10,2002-07-27 12:00:00,32.041667,-105.958333,230.837110,16.730193,1.078139,1
11,2002-07-28 12:00:00,34.916667,-107.833333,114.910720,9.697703,1.092172,0
12,2002-07-29 12:00:00,34.916667,-107.875000,109.863980,5.064829,1.048329,0
13,2002-07-29 12:00:00,34.916667,-107.833333,121.610410,16.397395,1.155849,0
14,2002-10-02 12:00:00,40.916667,-110.625000,139.816310,4.783127,1.035422,0
15,2002-10-02 12:00:00,40.916667,-110.583333,128.448200,0.650914,1.005093,0
16,2002-10-14 12:00:00,42.750000,-77.833333,269.735700,74.231887,1.379695,1
17,2002-10-15 12:00:00,42.750000,-77.833333,269.735700,74.231887,1.379695,0
18,2002-11-10 12:00:00,35.541667,-118.416667,321.635200,3.112746,1.009772,0
19,2002-11-10 12:00:00,35.541667,-118.375000,323.340580,2.096611,1.006527,0
20,2002-11-21 12:00:00,36.166667,-82.458333,277.977500,76.226509,1.377825,0
21,2002-11-22 12:00:00,36.166667,-82.458333,283.552550,81.801551,1.405458,0
22,2002-12-25 12:00:00,33.375000,-111.750000,193.123730,56.066911,1.409078,1
23,2002-12-25 12:00:00,33.375000,-111.708333,138.342010,2.532536,1.018648,1
24,2002-12-26 12:00:00,33.375000,-111.750000,179.945890,42.889070,1.312929,0
25,2002-09-12 12:00:00,46.166667,-69.583333,219.497960,2.785155,1.012852,1
26,2002-09-13 12:00:00,46.166667,-69.583333,219.562270,2.849471,1.013149,2
27,2002-09-11 12:00:00,34.708333,-108.125000,118.348290,7.791641,1.070476,1
28,2002-09-11 12:00:00,34.750000,-108.125000,119.604800,8.030142,1.071971,1
29,2002-09-11 12:00:00,34.791667,-108.125000,132.236180,20.002022,1.178217,1
30,2002-09-11 12:00:00,34.791667,-108.083333,130.211150,20.844714,1.190595,1
31,2002-09-11 12:00:00,34.791667,-108.041667,110.829285,3.899548,1.036468,1
32,2002-09-11 12:00:00,34.833333,-108.125000,128.559520,15.792340,1.140044,1
33,2002-09-11 12:00:00,34.833333,-108.083333,129.700790,20.131041,1.183728,1
34,2002-09-11 12:00:00,34.500000,-108.125000,106.534320,1.829355,1.017472,1
35,2002-09-11 12:00:00,34.500000,-108.083333,111.590320,3.031065,1.027921,1
36,2002-09-11 12:00:00,34.541667,-108.125000,109.372190,3.972729,1.037692,1
37,2002-09-11 12:00:00,34.583333,-108.125000,110.817055,5.845976,1.055691,1
38,2002-09-11 12:00:00,34.583333,-108.083333,105.418810,2.674490,1.026031,1
39,2002-09-11 12:00:00,34.541667,-108.208333,109.650345,0.866999,1.007970,1
40,2002-09-11 12:00:00,34.625000,-108.125000,120.382630,13.735705,1.128796,1
41,2002-09-11 12:00:00,34.666667,-108.125000,131.245820,22.696871,1.209093,1
42,2002-09-11 12:00:00,34.791667,-108.083333,130.211150,20.844714,1.190595,1
43,2002-09-12 12:00:00,34.500000,-108.125000,107.860170,3.155207,1.030134,0
44,2002-09-12 12:00:00,34.541667,-108.125000,114.330370,8.930904,1.084734,0
45,2002-09-12 12:00:00,34.583333,-108.125000,114.722770,9.751692,1.092899,0
46,2002-09-12 12:00:00,34.625000,-108.125000,112.106606,5.459681,1.051194,0
47,2002-09-12 12:00:00,34.666667,-108.125000,116.492840,7.943896,1.073183,0
48,2002-09-12 12:00:00,34.750000,-108.125000,118.092964,6.518309,1.058421,0
49,2002-09-12 12:00:00,34.791667,-108.125000,123.082756,10.848603,1.096660,0
50,2002-09-12 12:00:00,34.791667,-108.083333,117.414055,8.047618,1.073584,0

### subset down to just events for each threshold, for looping

In [6]:
events1000_48h = df1000_48h.drop_duplicates(['time','event_num'])
events100_48h = df100_48h.drop_duplicates(['time','event_num'])
events10_48h = df10_48h.drop_duplicates(['time','event_num'])

print("1000-yr events: "+str(len(events1000_48h)))
print("100-yr events: "+str(len(events100_48h)))
print("10-yr events: "+str(len(events10_48h)))

events1000_48h

1000-yr events: 12
100-yr events: 90
10-yr events: 516

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2002-03-18 12:00:00,36.625000,-82.458333,192.65015,10.208249,1.055953,0
2,2002-06-23 12:00:00,44.208333,-89.625000,258.13940,2.597104,1.010163,2
3,2002-07-06 12:00:00,41.000000,-101.833333,203.07721,6.430487,1.032701,2
7,2002-07-07 12:00:00,40.916667,-101.875000,200.65080,3.822579,1.019421,0
47,2002-08-21 12:00:00,47.958333,-106.791667,190.85732,8.129716,1.044491,2
49,2002-08-22 12:00:00,42.333333,-90.000000,247.60664,1.163800,1.004722,2
54,2002-08-22 12:00:00,47.958333,-106.791667,190.85732,8.129716,1.044491,4
56,2002-08-23 12:00:00,42.333333,-90.041667,247.13066,0.511508,1.002074,1
67,2002-09-15 12:00:00,31.000000,-84.958333,489.14832,9.962713,1.020791,0
74,2002-09-22 12:00:00,33.416667,-85.708333,339.06415,0.647228,1.001913,0
77,2002-09-23 12:00:00,33.416667,-86.333333,408.45486,16.357219,1.041717,0
79,2002-11-09 12:00:00,35.458333,-118.333333,311.93475,6.379834,1.020880,0

### now move the maps, so the ones retained at each ARI are in their own directories

In [7]:
os.system("mkdir -p "+dataset+"/auto_qc/48h/"+str(year)+"/maps/retained1000 "+dataset+"/auto_qc/48h/"+str(year)+"/maps/retained100 "+dataset+"/auto_qc/48h/"+str(year)+"/maps/retained10")

print("running 1000y")
for i, row in events1000_48h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/retained1000/.")

print("running 100y")
for i, row in events100_48h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/retained100/.")

print("running 10y")
for i, row in events10_48h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/retained10/.")

running 1000y
running 100y

mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062312_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070612_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082212_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002110912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002032012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002050912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002052412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002052512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060512_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061412_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061512_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062312_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062412_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070512_7.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070612_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070712_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070812_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070812_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070812_6.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070912_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072412_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002073012_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080712_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081012_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082212_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082212_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082712_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082712_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082712_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082912_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083012_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083112_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083112_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090712_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091312_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002100212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002100312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002110912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002111012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002121512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002121612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002051712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002051612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002063012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061912_0.png': No such file or directory

running 10y

mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002051912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002100912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002040812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002040912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002100412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002040412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002120412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002030312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002030412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002100812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002120512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002052812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002110512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002073012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002073112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002050612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002050712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002111612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002111712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002073012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002052612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002052712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002041912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002042012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002122412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002122512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002053112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070312_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002120412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002073112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002033112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002032012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002042612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002042712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002052512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002063012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070612_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002012512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070512_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091412_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002012112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002050412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002033112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002040812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002033112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002111012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002012412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002040912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002040112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060612_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072712_2.png': No such file or directory

### now repeat for the removed ones, sorting map files into directories for the highest ARI on which they were removed
#### note that some events have both retained and removed points. The ones with some retained points will have already been moved, so these will be just the events that were completely removed

In [8]:
removed_events1000_48h = removed1000_48h.drop_duplicates(['time','event_num'])
removed_events100_48h = removed100_48h.drop_duplicates(['time','event_num'])
removed_events10_48h = removed10_48h.drop_duplicates(['time','event_num'])

print("removed 1000-yr events: "+str(len(removed_events1000_48h)))
print("removed 100-yr events: "+str(len(removed_events100_48h)))
print("removed 10-yr events: "+str(len(removed_events10_48h)))

removed 1000-yr events: 19
removed 100-yr events: 39
removed 10-yr events: 186

In [9]:
os.system("mkdir -p "+dataset+"/auto_qc/48h/"+str(year)+"/maps/removed1000 "+dataset+"/auto_qc/48h/"+str(year)+"/maps/removed100 "+dataset+"/auto_qc/48h/"+str(year)+"/maps/removed10")

print("running 1000y")
for i, row in removed_events1000_48h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/removed1000/.")

print("running 100y")
for i, row in removed_events100_48h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/removed100/.")

print("running 10y")
for i, row in removed_events10_48h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/removed10/.")

running 1000y
running 100y

mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002100212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002111012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002112112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002112212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002122512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002122612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091312_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002013012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002013112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002042812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061412_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062412_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081012_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002100212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002100312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002103012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002111012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002111712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002112112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002112212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002120612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002120712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002122512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002122612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002122612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091312_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091212_0.png': No such file or directory

running 10y

mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002010512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002010612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002011212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002011312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002011512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002011612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002013012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002013112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002030312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002030412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002031912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002032012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002042212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002042312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002042812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002042812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002042912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002042912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002050512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002050612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002052812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002060812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061412_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002061912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062212_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062412_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062512_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002062912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002063012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070312_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070312_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070412_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070412_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070412_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070512_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070512_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070512_6.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070612_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070612_6.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070712_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070812_5.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070812_7.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070912_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002070912_6.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071512_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071712_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002071912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072012_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072412_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072612_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072612_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072712_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002072912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002073012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002073012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002073112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002080912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081012_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081312_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002081612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082312_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082712_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002082912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083012_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002083112_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002090912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091412_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002092612_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002100212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002100312_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002100712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002100812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002100812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002101912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102412_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002102912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002103012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002103112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002110912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002111012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002111512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002111612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002111712_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002111812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002112112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002112212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002112412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002112512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002120112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002120212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002120612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002120712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002121812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002121812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002121912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002122512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002122612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002122612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002122712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091312_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/48h/2002/maps/qc_check_2002091212_0.png': No such file or directory

## Pause here!

#### now, take a look at the maps for these cases (under "retained1000", for example)

#### if we want to remove a row because it's bad, specify the row(s) in the 1000-year dataframe

In [11]:
df1000_48h[df1000_48h.time=='2002-09-12 12:00:00']

Empty DataFrame
Columns: [time, lat, lon, tp, tp_minus_ari, tp_pct_of_ari, event_num]
Index: []

In [270]:
####           ### which index(es) to drop?
#to_drop = [0,1,2] + list(range(10,40))
           
           #### this needs to be user-specified based on manual inspection!!
to_drop = [0,1,2,3,4]
####

rows_to_drop_visual = df1000_48h.loc[to_drop]
rows_to_drop_visual

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2024-03-03 12:00:00,43.083333,-112.333333,84.008286,0.747086,1.008973,1
1,2024-04-05 12:00:00,45.916667,-116.125000,118.170395,6.511991,1.058321,0
2,2024-04-05 12:00:00,45.916667,-116.083333,120.530730,9.177128,1.082414,0
3,2024-04-05 12:00:00,45.958333,-116.125000,109.670334,2.228334,1.020740,0
4,2024-04-05 12:00:00,45.958333,-116.083333,109.994064,2.602864,1.024237,0

#### find any other points within a small radius around these (say 0.1 degrees in each direction)
#### furthermore, find points in the 100- and 10-year files on the same day and in the same radius, in all 3 durations (72,48,24)

In [271]:
latlon_buf = 0.10  ## lat/lon buffer around the centerpoint

rows_to_drop_1000_72h = removed1000_72h
rows_to_drop_100_72h = removed100_72h
rows_to_drop_10_72h = removed10_72h
rows_to_drop_1000_48h = removed1000_48h
rows_to_drop_100_48h = removed100_48h
rows_to_drop_10_48h = removed10_48h
rows_to_drop_1000_24h = removed1000_24h
rows_to_drop_100_24h = removed100_24h
rows_to_drop_10_24h = removed10_24h

for i in range(0,len(rows_to_drop_visual)):
    this_lon = rows_to_drop_visual.iloc[i].lon
    this_lat = rows_to_drop_visual.iloc[i].lat
    this_time = rows_to_drop_visual.iloc[i].time
    
    more_rows_to_drop_1000_72h = df1000_72h[(df1000_72h.time==this_time) & (df1000_72h.lon >= this_lon-latlon_buf) & (df1000_72h.lon <= this_lon+latlon_buf) & (df1000_72h.lat >= this_lat-latlon_buf) & (df1000_72h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_72h = pd.concat([rows_to_drop_1000_72h,more_rows_to_drop_1000_72h])

    ### now also find the rows in the same area in the 100 & 10-year files
    more_rows_to_drop_100_72h = df100_72h[(df100_72h.time==this_time) & (df100_72h.lon >= this_lon-latlon_buf) & (df100_72h.lon <= this_lon+latlon_buf) & (df100_72h.lat >= this_lat-latlon_buf) & (df100_72h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_72h = df10_72h[(df10_72h.time==this_time) & (df10_72h.lon >= this_lon-latlon_buf) & (df10_72h.lon <= this_lon+latlon_buf) & (df10_72h.lat >= this_lat-latlon_buf) & (df10_72h.lat <= this_lat+latlon_buf)] 

    rows_to_drop_100_72h = pd.concat([rows_to_drop_100_72h,more_rows_to_drop_100_72h])
    rows_to_drop_10_72h = pd.concat([rows_to_drop_10_72h,more_rows_to_drop_10_72h])  

    ### repeat for 48h
    more_rows_to_drop_1000_48h = df1000_48h[(df1000_48h.time==this_time) & (df1000_48h.lon >= this_lon-latlon_buf) & (df1000_48h.lon <= this_lon+latlon_buf) & (df1000_48h.lat >= this_lat-latlon_buf) & (df1000_48h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_48h = pd.concat([rows_to_drop_1000_48h,more_rows_to_drop_1000_48h])
    more_rows_to_drop_100_48h = df100_48h[(df100_48h.time==this_time) & (df100_48h.lon >= this_lon-latlon_buf) & (df100_48h.lon <= this_lon+latlon_buf) & (df100_48h.lat >= this_lat-latlon_buf) & (df100_48h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_48h = df10_48h[(df10_48h.time==this_time) & (df10_48h.lon >= this_lon-latlon_buf) & (df10_48h.lon <= this_lon+latlon_buf) & (df10_48h.lat >= this_lat-latlon_buf) & (df10_48h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_100_48h = pd.concat([rows_to_drop_100_48h,more_rows_to_drop_100_48h])
    rows_to_drop_10_48h = pd.concat([rows_to_drop_10_48h,more_rows_to_drop_10_48h])  

    ### and 24
    more_rows_to_drop_1000_24h = df1000_24h[(df1000_24h.time==this_time) & (df1000_24h.lon >= this_lon-latlon_buf) & (df1000_24h.lon <= this_lon+latlon_buf) & (df1000_24h.lat >= this_lat-latlon_buf) & (df1000_24h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_24h = pd.concat([rows_to_drop_1000_24h,more_rows_to_drop_1000_24h])
    
    ### now also find the rows in the same area in the 100 & 10-year files
    more_rows_to_drop_100_24h = df100_24h[(df100_24h.time==this_time) & (df100_24h.lon >= this_lon-latlon_buf) & (df100_24h.lon <= this_lon+latlon_buf) & (df100_24h.lat >= this_lat-latlon_buf) & (df100_24h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_24h = df10_24h[(df10_24h.time==this_time) & (df10_24h.lon >= this_lon-latlon_buf) & (df10_24h.lon <= this_lon+latlon_buf) & (df10_24h.lat >= this_lat-latlon_buf) & (df10_24h.lat <= this_lat+latlon_buf)] 
    
    rows_to_drop_100_24h = pd.concat([rows_to_drop_100_24h,more_rows_to_drop_100_24h])
    rows_to_drop_10_24h = pd.concat([rows_to_drop_10_24h,more_rows_to_drop_10_24h])  

#### drop duplicates
rows_to_drop_1000_72h = rows_to_drop_1000_72h.drop_duplicates()
rows_to_drop_100_72h.drop_duplicates(inplace=True)
rows_to_drop_10_72h.drop_duplicates(inplace=True)
rows_to_drop_1000_48h = rows_to_drop_1000_48h.drop_duplicates()
rows_to_drop_100_48h.drop_duplicates(inplace=True)
rows_to_drop_10_48h.drop_duplicates(inplace=True)
rows_to_drop_1000_24h = rows_to_drop_1000_24h.drop_duplicates()
rows_to_drop_100_24h.drop_duplicates(inplace=True)
rows_to_drop_10_24h.drop_duplicates(inplace=True)

rows_to_drop_100_48h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2024-01-14 12:00:00,42.333333,-115.875000,72.27330,2.651900,1.038090,1
1,2024-01-14 12:00:00,42.333333,-115.833333,69.64991,1.247710,1.018241,1
2,2024-01-14 12:00:00,42.375000,-115.916667,75.63413,5.174532,1.073440,1
3,2024-01-14 12:00:00,42.375000,-115.875000,77.47375,8.614347,1.125101,1
4,2024-01-14 12:00:00,42.375000,-115.833333,73.78732,6.324922,1.093755,1
...,...,...,...,...,...,...,...
187,2024-04-05 12:00:00,45.833333,-116.000000,106.28595,13.042546,1.139876,0
196,2024-04-05 12:00:00,45.875000,-116.000000,98.96532,8.160313,1.089866,0
204,2024-04-05 12:00:00,45.916667,-116.000000,95.40732,9.910915,1.115922,0
212,2024-04-05 12:00:00,45.958333,-116.000000,91.73596,8.779561,1.105833,0
218,2024-04-05 12:00:00,46.000000,-116.000000,84.60444,1.876638,1.022684,0

#### now drop those rows from the original dataframes. Method from here: https://www.includehelp.com/python/how-to-remove-rows-in-a-pandas-dataframe-if-the-same-row-exists-in-another-dataframe.aspx#:~:text=df1%20and%20df2.-,Remove%20rows%20in%20a%20Pandas%20dataframe%20if%20the%20same%20row,then%20drop%20the%20common%20rows.

In [272]:
df1000_72h_edit = pd.merge(df1000_72h,rows_to_drop_1000_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_72h_edit = pd.merge(df100_72h,rows_to_drop_100_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_72h_edit = pd.merge(df10_72h,rows_to_drop_10_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_72h length went from "+str(len(df1000_72h))+" to "+str(len(df1000_72h_edit)))
print("df100_72h length went from "+str(len(df100_72h))+" to "+str(len(df100_72h_edit)))
print("df10_72h length went from "+str(len(df10_72h))+" to "+str(len(df10_72h_edit)))

#### 48h
df1000_48h_edit = pd.merge(df1000_48h,rows_to_drop_1000_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_48h_edit = pd.merge(df100_48h,rows_to_drop_100_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_48h_edit = pd.merge(df10_48h,rows_to_drop_10_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_48h length went from "+str(len(df1000_48h))+" to "+str(len(df1000_48h_edit)))
print("df100_48h length went from "+str(len(df100_48h))+" to "+str(len(df100_48h_edit)))
print("df10_48h length went from "+str(len(df10_48h))+" to "+str(len(df10_48h_edit)))

### 24h
df1000_24h_edit = pd.merge(df1000_24h,rows_to_drop_1000_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_24h_edit = pd.merge(df100_24h,rows_to_drop_100_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_24h_edit = pd.merge(df10_24h,rows_to_drop_10_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_24h length went from "+str(len(df1000_24h))+" to "+str(len(df1000_24h_edit)))
print("df100_24h length went from "+str(len(df100_24h))+" to "+str(len(df100_24h_edit)))
print("df10_24h length went from "+str(len(df10_24h))+" to "+str(len(df10_24h_edit)))

df1000_72h length went from 877 to 877
df100_72h length went from 9266 to 9230
df10_72h length went from 104626 to 104566
df1000_48h length went from 462 to 457
df100_48h length went from 5588 to 5535
df10_48h length went from 66911 to 66850
df1000_24h length went from 33 to 33
df100_24h length went from 2171 to 2171
df10_24h length went from 28502 to 28497

In [273]:
df1000_72h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y72h_edit.csv", index=False)
df100_72h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y72h_edit.csv", index=False)
df10_72h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y72h_edit.csv", index=False)

rows_to_drop_1000_72h.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y72h.csv", index=False)
rows_to_drop_100_72h.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y72h.csv", index=False)
rows_to_drop_10_72h.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y72h.csv", index=False)
                             
#### 48h
df1000_48h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y48h_edit.csv", index=False)
df100_48h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y48h_edit.csv", index=False)
df10_48h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y48h_edit.csv", index=False)

rows_to_drop_1000_48h.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y48h.csv", index=False)
rows_to_drop_100_48h.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y48h.csv", index=False)
rows_to_drop_10_48h.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y48h.csv", index=False)  

### 24h
df1000_24h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y24h_edit.csv", index=False)
df100_24h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y24h_edit.csv", index=False)
df10_24h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y24h_edit.csv", index=False)

rows_to_drop_1000_24h.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y24h.csv", index=False)
rows_to_drop_100_24h.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y24h.csv", index=False)
rows_to_drop_10_24h.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y24h.csv", index=False)