### Now move on to 1000-yr, 24-h 

### do this after running the automated QC with "find_exceedances_qc_vs_prism", and running steps 2 and 3 (72 and 48 h)

In [1]:
import pandas as pd
import os

In [253]:
duration = 24
dataset = "stage4" ### which dataset to analyze

year = 2024

workdir = "/glade/work/rschumac/precip_data/extremerain/"

#### read in the exceedance files into pandas dataframes - note that now we're reading in the cleaned, edited files

In [254]:
df100_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y72h_edit.csv")
df10_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y72h_edit.csv")
try:
    df1000_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y72h_edit.csv")
except:  ## if no rows, just make an empty dataframe with the right columns
    df1000_72h = pd.DataFrame(columns=df_72h.columns)

### and the 48-h ones
df100_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y48h_edit.csv")
df10_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y48h_edit.csv")
try:
    df1000_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y48h_edit.csv")
except:
    df1000_48h = pd.DataFrame(columns=df_48h.columns)

### and the 24-h ones
df100_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y24h_edit.csv")
df10_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y24h_edit.csv")
try:
    df1000_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y24h_edit.csv")
except:
    df1000_24h = pd.DataFrame(columns=df_48h.columns)

In [255]:
df1000_24h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2024-03-16 12:00:00,38.125000,-111.416667,138.33026,0.034566,1.000250,1
1,2024-06-10 12:00:00,34.958333,-105.333333,151.98210,2.425478,1.016218,0
2,2024-06-19 12:00:00,36.625000,-101.500000,215.00714,1.025230,1.004791,0
3,2024-06-19 12:00:00,36.625000,-101.458333,230.19824,14.694026,1.068184,0
4,2024-06-19 12:00:00,36.666667,-101.458333,237.63637,21.978949,1.101916,0
5,2024-06-19 12:00:00,36.666667,-101.416667,227.33658,10.332919,1.047616,0
6,2024-06-19 12:00:00,37.125000,-101.208333,224.85360,1.129413,1.005048,0
7,2024-06-20 12:00:00,34.500000,-106.000000,138.93918,6.963671,1.052765,1
8,2024-06-20 12:00:00,34.500000,-105.958333,152.39610,21.817524,1.167083,1
9,2024-06-20 12:00:00,34.500000,-105.916667,129.88463,0.115510,1.000890,1
10,2024-06-20 12:00:00,34.500000,-105.875000,135.72241,5.340544,1.040961,1
11,2024-06-20 12:00:00,34.500000,-105.833333,132.72737,0.286789,1.002165,1
12,2024-06-20 12:00:00,34.541667,-106.000000,147.24884,18.877869,1.147057,1
13,2024-06-20 12:00:00,34.541667,-105.958333,197.49112,68.634206,1.532639,1
14,2024-06-20 12:00:00,34.541667,-105.916667,207.08017,77.868152,1.602639,1
15,2024-06-20 12:00:00,34.541667,-105.875000,212.25990,82.081149,1.630526,1
16,2024-06-20 12:00:00,34.541667,-105.833333,198.77495,67.351256,1.512474,1
17,2024-06-20 12:00:00,34.583333,-105.958333,141.13226,14.941034,1.118400,1
18,2024-06-20 12:00:00,34.583333,-105.916667,180.60562,53.523029,1.421167,1
19,2024-06-20 12:00:00,34.583333,-105.875000,177.71815,49.113376,1.381894,1
20,2024-06-20 12:00:00,34.583333,-105.833333,153.19923,23.376972,1.180069,1
21,2024-06-20 12:00:00,35.750000,-105.250000,162.32393,5.376911,1.034259,1
22,2024-06-20 12:00:00,35.791667,-105.333333,159.49889,8.752747,1.058063,1
23,2024-06-20 12:00:00,35.791667,-105.291667,178.29758,25.763832,1.168906,1
24,2024-06-21 12:00:00,43.250000,-96.958333,220.14178,1.156541,1.005281,2
25,2024-06-21 12:00:00,43.291667,-96.708333,230.60368,12.145095,1.055594,2
26,2024-06-21 12:00:00,43.291667,-96.666667,234.09454,14.818634,1.067580,2
27,2024-06-21 12:00:00,43.291667,-96.625000,221.83597,1.413501,1.006413,2
28,2024-06-21 12:00:00,43.333333,-96.666667,217.86206,0.007642,1.000035,2
29,2024-06-30 12:00:00,34.625000,-106.291667,136.64620,2.714013,1.020264,0
30,2024-09-26 12:00:00,35.666667,-82.583333,189.51344,6.076947,1.033128,0
31,2024-09-27 12:00:00,35.583333,-82.375000,262.23328,20.539323,1.084981,0
32,2024-11-27 12:00:00,38.416667,-112.333333,132.06334,3.380333,1.026269,0

#### and the files with the removed points, output from the automated QC algorithm

In [256]:
removed1000_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y72h.csv")
removed100_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y72h.csv")
removed10_72h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y72h.csv")

removed1000_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y48h.csv")
removed100_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y48h.csv")
removed10_48h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y48h.csv")

removed1000_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y24h.csv")
removed100_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y24h.csv")
removed10_24h = pd.read_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y24h.csv")

removed1000_24h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2024-03-16 12:00:00,37.916667,-110.750000,208.05280,102.059551,1.962887,1
1,2024-03-16 12:00:00,38.083333,-110.875000,173.21129,66.212892,1.618821,1
2,2024-03-16 12:00:00,38.125000,-111.625000,134.06450,4.232420,1.032599,1
3,2024-03-16 12:00:00,38.125000,-111.583333,147.97691,13.225837,1.098150,1
4,2024-03-16 12:00:00,38.125000,-111.458333,156.50615,14.779277,1.104280,1
5,2024-03-16 12:00:00,38.125000,-110.875000,218.89510,111.498676,2.038197,1
6,2024-03-16 12:00:00,38.125000,-110.833333,251.43706,115.620280,1.851296,1
7,2024-03-16 12:00:00,38.166667,-111.583333,128.29918,3.199507,1.025576,1
8,2024-03-16 12:00:00,38.166667,-111.541667,142.63486,4.038014,1.029135,1
9,2024-03-16 12:00:00,38.166667,-111.500000,151.57903,9.415723,1.066232,1
10,2024-03-16 12:00:00,38.166667,-111.458333,155.95192,15.680284,1.111785,1
11,2024-03-16 12:00:00,38.166667,-111.416667,162.96378,30.620743,1.231374,1
12,2024-03-16 12:00:00,38.166667,-111.375000,131.96812,9.209264,1.075019,1
13,2024-03-16 12:00:00,38.166667,-110.916667,122.58844,32.236486,1.356788,1
14,2024-03-16 12:00:00,38.166667,-110.875000,259.87094,165.720861,2.760178,1
15,2024-03-16 12:00:00,38.166667,-110.833333,237.28890,136.446430,2.353065,1
16,2024-03-16 12:00:00,38.208333,-111.541667,140.13180,10.008116,1.076912,1
17,2024-03-16 12:00:00,38.208333,-111.500000,139.74687,3.957505,1.029144,1
18,2024-03-16 12:00:00,38.208333,-111.416667,124.30427,7.978433,1.068587,1
19,2024-03-16 12:00:00,38.250000,-111.541667,129.01730,19.598732,1.179117,1
20,2024-03-16 12:00:00,38.250000,-111.500000,114.59217,3.148263,1.028250,1
21,2024-03-16 12:00:00,38.291667,-111.541667,94.76454,8.644680,1.100380,1
22,2024-06-20 12:00:00,36.041667,-106.333333,148.68360,16.706535,1.126587,1
23,2024-06-20 12:00:00,36.041667,-106.291667,139.89175,18.729315,1.154580,1
24,2024-06-20 12:00:00,36.083333,-106.291667,133.30641,13.424589,1.111982,1
25,2024-06-21 12:00:00,36.000000,-106.291667,130.18701,4.587079,1.036521,1
26,2024-11-27 12:00:00,38.166667,-112.166667,93.51695,4.227165,1.047342,0
27,2024-03-16 12:00:00,38.000000,-110.833333,168.94899,60.647537,1.559988,1
28,2024-03-16 12:00:00,38.000000,-110.791667,167.81480,54.445672,1.480251,1
29,2024-03-16 12:00:00,38.041667,-110.833333,137.65382,5.185954,1.039149,1
30,2024-03-16 12:00:00,38.083333,-110.833333,194.09116,54.422873,1.389658,1

### subset down to just events for each threshold, for looping

In [257]:
events1000_24h = df1000_24h.drop_duplicates(['time','event_num'])
events100_24h = df100_24h.drop_duplicates(['time','event_num'])
events10_24h = df10_24h.drop_duplicates(['time','event_num'])

print("1000-yr events: "+str(len(events1000_24h)))
print("100-yr events: "+str(len(events100_24h)))
print("10-yr events: "+str(len(events10_24h)))

events1000_24h

1000-yr events: 9
100-yr events: 50
10-yr events: 276

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2024-03-16 12:00:00,38.125000,-111.416667,138.33026,0.034566,1.000250,1
1,2024-06-10 12:00:00,34.958333,-105.333333,151.98210,2.425478,1.016218,0
2,2024-06-19 12:00:00,36.625000,-101.500000,215.00714,1.025230,1.004791,0
7,2024-06-20 12:00:00,34.500000,-106.000000,138.93918,6.963671,1.052765,1
24,2024-06-21 12:00:00,43.250000,-96.958333,220.14178,1.156541,1.005281,2
29,2024-06-30 12:00:00,34.625000,-106.291667,136.64620,2.714013,1.020264,0
30,2024-09-26 12:00:00,35.666667,-82.583333,189.51344,6.076947,1.033128,0
31,2024-09-27 12:00:00,35.583333,-82.375000,262.23328,20.539323,1.084981,0
32,2024-11-27 12:00:00,38.416667,-112.333333,132.06334,3.380333,1.026269,0

### now move the maps, so the ones retained at each ARI are in their own directories

In [258]:
os.system("mkdir -p "+dataset+"/auto_qc/24h/"+str(year)+"/maps/retained1000 "+dataset+"/auto_qc/24h/"+str(year)+"/maps/retained100 "+dataset+"/auto_qc/24h/"+str(year)+"/maps/retained10")

print("running 1000y")
for i, row in events1000_24h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/retained1000/.")

print("running 100y")
for i, row in events100_24h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/retained100/.")

print("running 10y")
for i, row in events10_24h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/retained10/.")

running 1000y
running 100y

mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024031612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024061012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024061912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024063012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024092612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024092712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024112712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024061312_0.png': No such file or directory

running 10y

mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024080512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024101012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024080612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024092712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024041012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024050212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024110712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024092612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024110812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024082712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024080912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024102012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024042812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024061012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024091712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024020512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024050412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024063012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024050912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024020712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024110412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024110512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024092812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024061912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024091812_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024031612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024112712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024112112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024042712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024071012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024081912_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024052112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062112_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024040512_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024071612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024030212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024092512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024071112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024073012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024091912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024081512_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024061912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024091712_4.png': No such file or directory

### now repeat for the removed ones, sorting map files into directories for the highest ARI on which they were removed
#### note that some events have both retained and removed points. The ones with some retained points will have already been moved, so these will be just the events that were completely removed

In [259]:
removed_events1000_24h = removed1000_24h.drop_duplicates(['time','event_num'])
removed_events100_24h = removed100_24h.drop_duplicates(['time','event_num'])
removed_events10_24h = removed10_24h.drop_duplicates(['time','event_num'])

print("removed 1000-yr events: "+str(len(removed_events1000_24h)))
print("removed 100-yr events: "+str(len(removed_events100_24h)))
print("removed 10-yr events: "+str(len(removed_events10_24h)))

removed 1000-yr events: 4
removed 100-yr events: 13
removed 10-yr events: 78

In [260]:
os.system("mkdir -p "+dataset+"/auto_qc/24h/"+str(year)+"/maps/removed1000 "+dataset+"/auto_qc/24h/"+str(year)+"/maps/removed100 "+dataset+"/auto_qc/24h/"+str(year)+"/maps/removed10")

print("running 1000y")
for i, row in removed_events1000_24h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/removed1000/.")

print("running 100y")
for i, row in removed_events100_24h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/removed100/.")

print("running 10y")
for i, row in removed_events10_24h.iterrows():
    time_pd = pd.to_datetime(row.time)
    os.system("mv "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/qc_check_"+time_pd.strftime("%Y%m%d%H")+"_"+str(row.event_num).zfill(1)+".png "+dataset+"/auto_qc/"+str(duration).zfill(2)+"h/"+str(year)+"/maps/removed10/.")

mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024031612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024112712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024020712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024031612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024031612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024040412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024041612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024061312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024070212_0.png': No such file or directory

running 1000y
running 100y
running 10y

mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024091712_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024112712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024011012_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024011412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024020212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024020312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024020712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024020812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024020812_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024031612_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024031612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024031712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024040112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024040412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024041012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024041612_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024050212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024051812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024052812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024060912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024061312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062112_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024062812_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024070212_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024072112_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024080912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024081212_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024081312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024081312_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024081412_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024081912_2.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024082212_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024082312_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024082712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024083012_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024091712_4.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024091812_3.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024091912_1.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024112712_0.png': No such file or directory
mv: cannot stat 'stage4/auto_qc/24h/2024/maps/qc_check_2024040512_0.png': No such file or directory

## Pause here!

#### now, take a look at the maps for these cases (under "retained1000", for example)

#### if we want to remove a row because it's bad, specify the row(s) in the 1000-year dataframe

In [262]:
df1000_24h[df1000_24h.time=='2024-11-27 12:00:00']

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
32,2024-11-27 12:00:00,38.416667,-112.333333,132.06334,3.380333,1.026269,0

In [264]:
####           ### which index(es) to drop?
#to_drop = [0,1,2] + list(range(10,40))
           
           #### this needs to be user-specified based on manual inspection!!
to_drop = [0,32]
####

rows_to_drop_visual = df1000_24h.loc[to_drop]
rows_to_drop_visual

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2024-03-16 12:00:00,38.125000,-111.416667,138.33026,0.034566,1.000250,1
32,2024-11-27 12:00:00,38.416667,-112.333333,132.06334,3.380333,1.026269,0

#### find any other points within a small radius around these (say 0.1 degrees in each direction)
#### furthermore, find points in the 100- and 10-year files on the same day and in the same radius, in all 3 durations (72,48,24)

In [265]:
latlon_buf = 0.1  ## lat/lon buffer around the centerpoint

rows_to_drop_1000_72h = removed1000_72h
rows_to_drop_100_72h = removed100_72h
rows_to_drop_10_72h = removed10_72h
rows_to_drop_1000_48h = removed1000_48h
rows_to_drop_100_48h = removed100_48h
rows_to_drop_10_48h = removed10_48h
rows_to_drop_1000_24h = removed1000_24h
rows_to_drop_100_24h = removed100_24h
rows_to_drop_10_24h = removed10_24h

for i in range(0,len(rows_to_drop_visual)):
    this_lon = rows_to_drop_visual.iloc[i].lon
    this_lat = rows_to_drop_visual.iloc[i].lat
    this_time = rows_to_drop_visual.iloc[i].time
    
    more_rows_to_drop_1000_72h = df1000_72h[(df1000_72h.time==this_time) & (df1000_72h.lon >= this_lon-latlon_buf) & (df1000_72h.lon <= this_lon+latlon_buf) & (df1000_72h.lat >= this_lat-latlon_buf) & (df1000_72h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_72h = pd.concat([rows_to_drop_1000_72h,more_rows_to_drop_1000_72h])

    ### now also find the rows in the same area in the 100 & 10-year files
    more_rows_to_drop_100_72h = df100_72h[(df100_72h.time==this_time) & (df100_72h.lon >= this_lon-latlon_buf) & (df100_72h.lon <= this_lon+latlon_buf) & (df100_72h.lat >= this_lat-latlon_buf) & (df100_72h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_72h = df10_72h[(df10_72h.time==this_time) & (df10_72h.lon >= this_lon-latlon_buf) & (df10_72h.lon <= this_lon+latlon_buf) & (df10_72h.lat >= this_lat-latlon_buf) & (df10_72h.lat <= this_lat+latlon_buf)] 

    rows_to_drop_100_72h = pd.concat([rows_to_drop_100_72h,more_rows_to_drop_100_72h])
    rows_to_drop_10_72h = pd.concat([rows_to_drop_10_72h,more_rows_to_drop_10_72h])  

    ### repeat for 48h
    more_rows_to_drop_1000_48h = df1000_48h[(df1000_48h.time==this_time) & (df1000_48h.lon >= this_lon-latlon_buf) & (df1000_48h.lon <= this_lon+latlon_buf) & (df1000_48h.lat >= this_lat-latlon_buf) & (df1000_48h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_48h = pd.concat([rows_to_drop_1000_48h,more_rows_to_drop_1000_48h])
    more_rows_to_drop_100_48h = df100_48h[(df100_48h.time==this_time) & (df100_48h.lon >= this_lon-latlon_buf) & (df100_48h.lon <= this_lon+latlon_buf) & (df100_48h.lat >= this_lat-latlon_buf) & (df100_48h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_48h = df10_48h[(df10_48h.time==this_time) & (df10_48h.lon >= this_lon-latlon_buf) & (df10_48h.lon <= this_lon+latlon_buf) & (df10_48h.lat >= this_lat-latlon_buf) & (df10_48h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_100_48h = pd.concat([rows_to_drop_100_48h,more_rows_to_drop_100_48h])
    rows_to_drop_10_48h = pd.concat([rows_to_drop_10_48h,more_rows_to_drop_10_48h])  

    ### and 24
    more_rows_to_drop_1000_24h = df1000_24h[(df1000_24h.time==this_time) & (df1000_24h.lon >= this_lon-latlon_buf) & (df1000_24h.lon <= this_lon+latlon_buf) & (df1000_24h.lat >= this_lat-latlon_buf) & (df1000_24h.lat <= this_lat+latlon_buf)] 
    rows_to_drop_1000_24h = pd.concat([rows_to_drop_1000_24h,more_rows_to_drop_1000_24h])
    
    ### now also find the rows in the same area in the 100 & 10-year files
    more_rows_to_drop_100_24h = df100_24h[(df100_24h.time==this_time) & (df100_24h.lon >= this_lon-latlon_buf) & (df100_24h.lon <= this_lon+latlon_buf) & (df100_24h.lat >= this_lat-latlon_buf) & (df100_24h.lat <= this_lat+latlon_buf)] 
    more_rows_to_drop_10_24h = df10_24h[(df10_24h.time==this_time) & (df10_24h.lon >= this_lon-latlon_buf) & (df10_24h.lon <= this_lon+latlon_buf) & (df10_24h.lat >= this_lat-latlon_buf) & (df10_24h.lat <= this_lat+latlon_buf)] 
    
    rows_to_drop_100_24h = pd.concat([rows_to_drop_100_24h,more_rows_to_drop_100_24h])
    rows_to_drop_10_24h = pd.concat([rows_to_drop_10_24h,more_rows_to_drop_10_24h])  

#### drop duplicates
rows_to_drop_1000_72h = rows_to_drop_1000_72h.drop_duplicates()
rows_to_drop_100_72h.drop_duplicates(inplace=True)
rows_to_drop_10_72h.drop_duplicates(inplace=True)
rows_to_drop_1000_48h = rows_to_drop_1000_48h.drop_duplicates()
rows_to_drop_100_48h.drop_duplicates(inplace=True)
rows_to_drop_10_48h.drop_duplicates(inplace=True)
rows_to_drop_1000_24h = rows_to_drop_1000_24h.drop_duplicates()
rows_to_drop_100_24h.drop_duplicates(inplace=True)
rows_to_drop_10_24h.drop_duplicates(inplace=True)

rows_to_drop_100_24h

,time,lat,lon,tp,tp_minus_ari,tp_pct_of_ari,event_num
0,2024-02-07 12:00:00,37.916667,-110.750000,102.44758,28.559623,1.386526,0
1,2024-02-07 12:00:00,38.000000,-110.833333,82.38762,7.494434,1.100068,0
2,2024-02-07 12:00:00,38.000000,-110.791667,82.21107,3.887420,1.049633,0
3,2024-02-07 12:00:00,38.166667,-110.875000,86.68771,21.169165,1.323102,0
4,2024-02-07 12:00:00,38.166667,-110.833333,75.79134,5.836502,1.083432,0
...,...,...,...,...,...,...,...
2164,2024-11-27 12:00:00,38.375000,-112.333333,131.96605,17.790839,1.155821,0
2165,2024-11-27 12:00:00,38.416667,-112.416667,131.00317,6.635323,1.053352,0
2166,2024-11-27 12:00:00,38.416667,-112.375000,151.65611,31.956326,1.266971,0
2167,2024-11-27 12:00:00,38.416667,-112.333333,132.06334,38.505925,1.411575,0
2168,2024-11-27 12:00:00,38.416667,-112.291667,73.71093,11.773437,1.190086,0

#### now drop those rows from the original dataframes. Method from here: https://www.includehelp.com/python/how-to-remove-rows-in-a-pandas-dataframe-if-the-same-row-exists-in-another-dataframe.aspx#:~:text=df1%20and%20df2.-,Remove%20rows%20in%20a%20Pandas%20dataframe%20if%20the%20same%20row,then%20drop%20the%20common%20rows.

In [266]:
df1000_72h_edit = pd.merge(df1000_72h,rows_to_drop_1000_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_72h_edit = pd.merge(df100_72h,rows_to_drop_100_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_72h_edit = pd.merge(df10_72h,rows_to_drop_10_72h,indicator=True,how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_72h length went from "+str(len(df1000_72h))+" to "+str(len(df1000_72h_edit)))
print("df100_72h length went from "+str(len(df100_72h))+" to "+str(len(df100_72h_edit)))
print("df10_72h length went from "+str(len(df10_72h))+" to "+str(len(df10_72h_edit)))

#### 48h
df1000_48h_edit = pd.merge(df1000_48h,rows_to_drop_1000_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_48h_edit = pd.merge(df100_48h,rows_to_drop_100_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_48h_edit = pd.merge(df10_48h,rows_to_drop_10_48h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_48h length went from "+str(len(df1000_48h))+" to "+str(len(df1000_48h_edit)))
print("df100_48h length went from "+str(len(df100_48h))+" to "+str(len(df100_48h_edit)))
print("df10_48h length went from "+str(len(df10_48h))+" to "+str(len(df10_48h_edit)))

### 24h
df1000_24h_edit = pd.merge(df1000_24h,rows_to_drop_1000_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df100_24h_edit = pd.merge(df100_24h,rows_to_drop_100_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)
df10_24h_edit = pd.merge(df10_24h,rows_to_drop_10_24h, indicator=True, how='outer').query('_merge=="left_only"').drop('_merge', axis=1)

print("df1000_24h length went from "+str(len(df1000_24h))+" to "+str(len(df1000_24h_edit)))
print("df100_24h length went from "+str(len(df100_24h))+" to "+str(len(df100_24h_edit)))
print("df10_24h length went from "+str(len(df10_24h))+" to "+str(len(df10_24h_edit)))

df1000_72h length went from 877 to 877
df100_72h length went from 9230 to 9218
df10_72h length went from 104566 to 104534
df1000_48h length went from 457 to 456
df100_48h length went from 5535 to 5519
df10_48h length went from 66850 to 66814
df1000_24h length went from 33 to 31
df100_24h length went from 2171 to 2153
df10_24h length went from 28497 to 28466

In [267]:
df1000_72h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y72h_edit.csv", index=False)
df100_72h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y72h_edit.csv", index=False)
df10_72h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y72h_edit.csv", index=False)

rows_to_drop_1000_72h.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y72h.csv", index=False)
rows_to_drop_100_72h.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y72h.csv", index=False)
rows_to_drop_10_72h.to_csv(workdir+"/"+dataset+"/auto_qc/72h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y72h.csv", index=False)
                             
#### 48h
df1000_48h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y48h_edit.csv", index=False)
df100_48h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y48h_edit.csv", index=False)
df10_48h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y48h_edit.csv", index=False)

rows_to_drop_1000_48h.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y48h.csv", index=False)
rows_to_drop_100_48h.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y48h.csv", index=False)
rows_to_drop_10_48h.to_csv(workdir+"/"+dataset+"/auto_qc/48h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y48h.csv", index=False)  

### 24h
df1000_24h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_1000y24h_edit.csv", index=False)
df100_24h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_100y24h_edit.csv", index=False)
df10_24h_edit.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_cleaned_10y24h_edit.csv", index=False)

rows_to_drop_1000_24h.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_1000y24h.csv", index=False)
rows_to_drop_100_24h.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_100y24h.csv", index=False)
rows_to_drop_10_24h.to_csv(workdir+"/"+dataset+"/auto_qc/24h/"+str(year)+"/"+dataset+"_"+str(year)+"_removed_points_10y24h.csv", index=False)